{
 "title": "Concurrent Http Client",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(fbb_http_client_requests_seconds_count, application)"
    }
   },
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(fbb_http_client_requests_seconds_count{application=\"$application\"}, method)"
    }
   },
   {
    "name": "uri",
    "label": "uri",
    "query": {
     "query": "label_values(fbb_http_client_requests_seconds_count, uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Concurrent Requests Overview      ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current Active",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\".*_http_client_requests_active\"})"
    }
   ]
  },
  {
   "title": "Average Concurrent (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  sum(\r\n    fbb_http_client_requests_active\r\n  )[1h:]\r\n)"
    }
   ]
  },
  {
   "title": "Peak Concurrent (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  sum(\r\n   {__name__=~\".*_http_client_requests_active\"}\r\n  )[1h:]\r\n)"
    }
   ]
  },
  {
   "title": "Global Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum ({__name__=~\".*_http_client_requests_active\"})",
     "legendFormat": "Current Active"
    }
   ]
  },
  { "title": "Concurrent Requests per API ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Concurrent Requests per API Endpoint   ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "\rsum by (uri,method)\r({__name__=~\".*_http_client_requests_active_per_api\", method=~\"$method\", uri=~\"$uri\"})",
     "legendFormat": "{{method}}{{uri}}"
    }
   ]
  },
  {
   "title": "Top 5 Most Concurrent APIs   ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  max_over_time(\r\n    sum by (uri, method) (\r\n      {__name__=~\".*_http_client_requests_active_per_api\",method=~\"$method\",uri=~\"$uri\"}\r\n    )[1h:]\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Concurrent Request Statistics per API   ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": " Concurrent Requests Statistics - Avg & Max per API",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(uri,method)({__name__=~\".*_http_client_requests_active_per_api\",method=~\"$method\",uri=~\"$uri\"})",
     "legendFormat": "{{uri}} {{method}}"
    },
    {
     "expr": "max_over_time(\r\n  sum by(uri,method)(\r\n   {__name__=~\".*_http_client_requests_active_per_api\",method=~\"$method\",uri=~\"$uri\"}\r\n  )[1h:]\r\n)",
     "legendFormat": "{{uri}} {{method}}"
    },
    {
     "expr": "avg_over_time(\r\n  sum by(uri,method)(\r\n    {__name__=~\".*_http_client_requests_active_per_api\",method=~\"$method\",uri=~\"$uri\"}\r\n  )[1h:]\r\n)",
     "legendFormat": "{{uri}} {{method}}"
    }
   ]
  },
  {
   "title": "Top 10 APIs by Average Concurrent Requests (Avg 1h)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  avg_over_time(\r\n    sum by (uri, method)(\r\n      {__name__=~\".*_http_client_requests_active_per_api\",method=~\"$method\",uri=~\"$uri\"}\r\n    )[1h:]\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 APIs by Peak Concurrent Requests (Max 1h)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  max_over_time(\r\n    sum by (uri, method)(\r\n      {__name__=~\".*_http_client_requests_active_per_api\",method=~\"$method\",uri=~\"$uri\"}\r\n    )[1h:]\r\n  )\r\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}