{
 "title": "Executor Metrics Dashboard",
 "description": " Executor Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(executor_tasks_total,application)"
    }
   },
   {
    "name": "executor",
    "label": "executor",
    "query": {
     "query": "label_values(executor_tasks_total{application=\"$application\"},executor)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queue Utilization Gauges",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_queue_utilization{executor=\"provisioning\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_queue_utilization{executor=\"async_provisioning\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_queue_utilization{executor=\"dependency_loader\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_queue_utilization{executor=\"http_client\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Utilization Gauges",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_pool_utilization{executor=\"provisioning\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_pool_utilization{executor=\"async_provisioning\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_pool_utilization{executor=\"dependency_loader\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_pool_utilization{executor=\"http_client\",application=~\"$application\"}",
     "legendFormat": "{{executor}}"
    }
   ]
  },
  {
   "title": "  Queue Size vs Capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "executor_queue_size{application=~\"$application\",executor=~\"$executor\"}",
     "legendFormat": "{{executor}} - Queue Size"
    },
    {
     "expr": "executor_queue_capacity{application=~\"$application\",executor=~\"$executor\"}",
     "legendFormat": "{{executor}} - Queue Capacity"
    }
   ]
  },
  {
   "title": "Queue Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_queue_remaining{application=~\"$application\",executor=\"async_provisioning\",}",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_queue_remaining{application=~\"$application\",executor=\"http_client\",}  ",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_queue_remaining{application=~\"$application\",executor=\"provisioning\",}  ",
     "legendFormat": "{{executor}}"
    },
    {
     "expr": "executor_queue_remaining{application=~\"$application\",executor=\"dependency_loader\"}  ",
     "legendFormat": "{{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Activity",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "executor_pool_active{application=~\"$application\",executor=~\"$executor\"}",
     "legendFormat": "{{executor}} - Active Threads"
    },
    {
     "expr": "executor_pool_size{application=~\"$application\",executor=~\"$executor\"}",
     "legendFormat": "{{executor}} - Pool Size"
    },
    {
     "expr": "executor_pool_max{application=~\"$application\",executor=~\"$executor\"}",
     "legendFormat": "{{executor}} - Max Pool Size"
    }
   ]
  },
  {
   "title": "TASK COMPLETION RATE (tasks/sec)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate (executor_tasks_completed{application=~\"$application\",executor=~\"$executor\"}[5m])",
     "legendFormat": "{{executor}} - Task Completion Rate"
    }
   ]
  },
  {
   "title": "Provisioning Queue Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_queue_remaining{executor=\"provisioning\"}"
    }
   ]
  },
  {
   "title": "Async Provisioning Queue Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_queue_remaining{executor=\"async_provisioning\"}"
    }
   ]
  },
  {
   "title": "Dependency Loader Queue Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_queue_remaining{executor=\"dependency_loader\"}"
    }
   ]
  },
  {
   "title": "HTTP Client Queue Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_queue_remaining{executor=\"http_client\"}"
    }
   ]
  },
  {
   "title": "Provisioning Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_tasks_completed{executor=\"provisioning\"}"
    }
   ]
  },
  {
   "title": "Provisioning Largest Pool Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_pool_largest{executor=\"provisioning\"}"
    }
   ]
  }
 ]
}