{
 "title": "outbound api (httpclient)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(http_client_requests_seconds_count,application)"
    }
   },
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_client_requests_seconds_count,uri)"
    }
   },
   {
    "name": "api",
    "query": {
     "query": "label_values(fbbfap_api_request_duration_seconds_count,uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary Request Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      http_client_requests_seconds_count{status=~\"2..\",uri=~\"$uri\"}[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      http_client_requests_seconds_count{status=~\"4..|5..\",uri=~\"$uri\"}[$__range]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      http_client_requests_seconds_count{uri=~\"$uri\"}[$__range]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Average Request TIme",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "legendFormat": "{{uri}}" },
    { "legendFormat": "{{uri}}" },
    {
     "expr": "1000* (sum by(uri)  (rate(http_client_requests_seconds_sum[$__range]))\r\n/\r\nsum by(uri)  (rate(http_client_requests_seconds_count[$__range])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "average time request uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000* (sum by(uri)  (rate(http_client_requests_seconds_sum[$__range]))\r\n/\r\nsum by(uri)  (rate(http_client_requests_seconds_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "floor(sum(increase(http_client_requests_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total failed requests ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(\r\n  sum(\r\n    increase(\r\n      http_client_requests_seconds_count{status=~\"4..|5..\"}[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total request by uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "floor(sum by (uri )(increase(http_client_requests_seconds_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average time request(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000* (sum  (rate(http_client_requests_seconds_sum[$__range]))\r\n/\r\nsum  (rate(http_client_requests_seconds_count[$__range])))",
     "legendFormat": "average time request"
    }
   ]
  },
  {
   "title": "Top slowest api latency P99",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.99, sum by (uri, le)(rate(http_server_requests_seconds_bucket[$__range]) ) ) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate by Uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (uri)(\r\n    rate(http_client_requests_seconds_count{status=~\"2..\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum by (uri)(\r\n    rate(http_client_requests_seconds_count[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    rate(http_client_requests_seconds_count{status=~\"2..\"}[$__rate_interval])\r\n  )\r\n)\r\n/\r\nclamp_min(\r\n  sum(\r\n    rate(http_client_requests_seconds_count[$__rate_interval])\r\n  ),\r\n  1\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    rate(http_client_requests_seconds_count{status=~\"4..|5..\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum(\r\n    rate(http_client_requests_seconds_count[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by uri",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by(uri)(\r\n    rate(http_client_requests_seconds_count{status=~\"4..|5..\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum by(uri)(\r\n    rate(http_client_requests_seconds_count[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "average time request  by uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000* (sum by (uri) (rate(http_client_requests_seconds_sum[$__range]))\r\n/\r\nsum by (uri) (rate(http_client_requests_seconds_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status)(http_client_requests_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Complete Task",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum by (executor) (rate(executor_tasks_completed[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Complete Task rate ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "100 * sum(\r\n  rate(executor_tasks_completed[$__rate_interval])\r\n)\r\n",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Retry rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_retry_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentiles (s)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket[$__range])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fbbfap_api_request_duration_seconds_bucket[$__range])) by (le))\r\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(fbbfap_api_request_duration_seconds_bucket[$__range])) by (le))\r\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Current Active request guage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 148 },
   "targets": [
    { "expr": "http_client_requests_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "failed requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_failed_total[$__range]))",
     "legendFormat": "request_failed"
    }
   ]
  }
 ]
}