{
 "title": "API Metrics-2",
 "tags": [
  "micrometer",
  "spring",
  "api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "env",
    "query": "label_values(fbbfap_api_request_duration_seconds_count, env)"
   },
   {
    "name": "api",
    "query": "label_values(fbbfap_api_request_duration_seconds_count{env=\"$env\"}, api)"
   }
  ]
 },
 "panels": [
  {
   "title": "Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{application=\"sky-fbbfap\"}"
    }
   ]
  },
  {
   "title": "Thread Pool Active",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"sky-fbbfap\"}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "executor_queue_remaining_tasks{name=\"mvcTaskExecutor\"}"
    }
   ]
  },
  {
   "title": "Completed Tasks / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total[1m])"
    }
   ]
  },
  {
   "title": "Retry Rate (req/sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_client_requests_retry_total[$__range])"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Pending Map Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_client_pending_map_size{application=\"sky-fbbfap\"}"
    }
   ]
  },
  {
   "title": "HTTP Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_server_requests_seconds_count)"
    }
   ]
  },
  {
   "title": "Total Requests Success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\".*_api_requests_total\",status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total request failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\".*_api_requests_total\",status=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests on range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range])))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Success Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "100 * sum(increase({__name__=~\".*_api_requests_total\", status=\"success\", env=\"$env\", api=~\"$api\"}[$__range])) / sum(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range]))",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "100 * (\r\n  sum (rate({__name__=~\".*_api_requests_total\", status=\"failed\", env=\"$env\"}[$__range]))\r\n) /\r\n(\r\n  sum(rate({__name__=~\".*_api_requests_total\", env=\"$env\"}[$__range]))\r\n)\r\n",
     "legendFormat": "error_rate"
    }
   ]
  },
  {
   "title": "Success Rate by api %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "100 * sum by(api )(increase({__name__=~\".*_api_requests_total\", status=\"success\", env=\"$env\", api=~\"$api\"}[$__range])) / sum by (api)(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by(api)(increase({__name__=~\".*_api_requests_total\", status=\"failed\", env=\"$env\"}[$__range]))\r\n     / sum by(api)(increase({__name__=~\".*_api_requests_total\", env=\"$env\"}[$__range]))\r\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "floor(sum by (status)(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests  by API",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "floor(\r\n  sum by (api) (\r\n    increase({__name__=~\".*_api_requests_total\", env=\"$env\"}[5m])\r\n  )\r\n)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Top APIs by p95 Latency",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  histogram_quantile(\r\n    0.95,\r\n    sum by (api, le)(\r\n      rate({__name__=~\".*_api_request_duration_seconds_bucket\", env=\"$env\"}[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Current p95 (s)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(fbbfap_api_request_duration_seconds_bucket{env=\"$env\", api=~\"$api\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Latency Percentiles (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(fbbfap_api_request_duration_seconds_bucket{env=\"$env\", api=~\"$api\"}[$__range])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(fbbfap_api_request_duration_seconds_bucket{env=\"$env\", api=~\"$api\"}[$__interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(fbbfap_api_request_duration_seconds_bucket{env=\"$env\", api=~\"$api\"}[$__interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Total Count Request",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "floor(sum by (api)(increase({__name__=~\".*_api_requests_total\",env=\"$env\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average time request",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(fbbfap_api_request_duration_seconds_sum[$__range]))\r\n/\r\nsum (rate(fbbfap_api_request_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average time request  by api",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000* (sum by (api) (rate(fbbfap_api_request_duration_seconds_sum[$__range]))\r\n/\r\nsum by (api) (rate(fbbfap_api_request_duration_seconds_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}