{
 "title": "inbound API   (app controller)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "env",
    "query": "label_values(fbbfap_api_request_duration_seconds_count, env)"
   },
   {
    "name": "api",
    "query": "label_values(fbbfap_api_request_duration_seconds_count{env=\"$env\"}, api)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary Request Time",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le, api) (\r\n    rate(fbbfap_api_request_duration_seconds_bucket[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "1000 *\r\nmax by (api) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, api) (\r\n      rate(fbbfap_api_request_duration_seconds_bucket[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "1000* (sum by (api) (rate(fbbfap_api_request_duration_seconds_sum[$__range]))\r\n/\r\nsum by (api) (rate(fbbfap_api_request_duration_seconds_count[$__range])))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "floor(\r\n  sum by (api) (\r\n    increase({__name__=~\".*_api_requests_total\", status=\"success\",api=~\"$api\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "floor(\r\n  sum by (api) (\r\n    increase({__name__=~\".*_api_requests_total\", status=\"failed\",api=~\"$api\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "floor(\r\n  sum by (api) (\r\n    increase({__name__=~\".*_api_requests_total\",api=~\"$api\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Total Requests on range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total request failed on range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\",status=\"failed\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "100 * sum(increase({__name__=~\".*_api_requests_total\", status=\"success\", env=\"$env\", api=~\"$api\"}[$__range])) / sum(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range]))",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "Success Rate by api %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "100 * sum by(api )(increase({__name__=~\".*_api_requests_total\", status=\"success\", env=\"$env\", api=~\"$api\"}[$__range])) / sum by (api)(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Count Request by api",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "floor(sum by (api)(increase({__name__=~\".*_api_requests_total\",env=\"$env\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top api request time",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  1000 *\r\n  (\r\n    sum by (api) (rate(fbbfap_api_request_duration_seconds_sum[$__range]))\r\n    /\r\n    sum by (api) (rate(fbbfap_api_request_duration_seconds_count[$__range]))\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average time request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(fbbfap_api_request_duration_seconds_sum[$__range]))\r\n/\r\nsum (rate(fbbfap_api_request_duration_seconds_count[$__range]))",
     "legendFormat": "fbbfap_api_request_duration"
    }
   ]
  },
  {
   "title": "average time request  by api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000* (sum by (api) (rate(fbbfap_api_request_duration_seconds_sum[$__range]))\r\n/\r\nsum by (api) (rate(fbbfap_api_request_duration_seconds_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "floor(sum by (status)(increase({__name__=~\".*_api_requests_total\", env=\"$env\", api=~\"$api\"}[$__range])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests  by API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "floor(\r\n  sum by (api) (\r\n    increase({__name__=~\".*_api_requests_total\", env=\"$env\"}[5m])\r\n  )\r\n)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Latency Percentiles (s)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(fbbfap_api_request_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fbbfap_api_request_duration_seconds_bucket[$__range])) by (le))\r\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(fbbfap_api_request_duration_seconds_bucket[$__range])) by (le))\r\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Summary HTTP Client Requests - Performance by Endpoint",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1000 *\r\n(\r\n  sum by (application, method, uri, status) (\r\n    rate(http_client_requests_seconds_sum{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum by (application, method, uri, status) (\r\n    rate(http_client_requests_seconds_count{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le,application, method, uri, status) (\r\n rate(http_client_requests_seconds_bucket{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nmax by (application, method, uri, status) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, application, method, uri, status) (\r\n rate(http_client_requests_seconds_bucket{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.50,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n      http_client_requests_seconds_bucket{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n      http_client_requests_seconds_bucket{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.99,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n      http_client_requests_seconds_bucket{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(\r\n  sum by (application, method, uri, status)(\r\n    increase(\r\n      http_client_requests_seconds_count{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r"
    }
   ]
  },
  {
   "title": "Summary HTTP Client Requests - Performance by Endpoint",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1000 *\r\n(\r\n  sum by (application, method, uri, status) (\r\n    rate(http_client_requests_seconds_sum{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum by (application, method, uri, status) (\r\n    rate(http_client_requests_seconds_count{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le,application, method, uri, status) (\r\n rate(http_client_requests_seconds_bucket{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nmax by (application, method, uri, status) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, application, method, uri, status) (\r\n rate(http_client_requests_seconds_bucket{application=\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.50,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n      http_client_requests_seconds_bucket{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n      http_client_requests_seconds_bucket{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.99,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n      http_client_requests_seconds_bucket{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(\r\n  sum by (application, method, uri, status)(\r\n    increase(\r\n      http_client_requests_seconds_count{\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r"
    }
   ]
  },
  {
   "title": "Top slowest api latency P99",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.99, sum by (api, le)( rate(fbbfap_api_request_duration_seconds_bucket{api=~\"$api\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}