{
 "title": "Fbb Api Provider Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(fbb_api_request_duration_seconds_count,application)"
    }
   },
   {
    "name": "api",
    "query": {
     "query": "label_values(fbb_api_request_duration_seconds_count{application=~\"$application\"},api)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate(Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\nsum(rate({__name__=~\".*_api_requests_total\", \nstatus=\"success\",\napplication=~\"$application\"}[1m]))\r\n    /\r\n    sum(rate({__name__=~\".*_api_requests_total\",application=~\"$application\"}[1m]))\r\n  ),\r\n  0\r\n)\n",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "Success Rate(Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\nsum(increase({__name__=~\".*_api_requests_total\", \nstatus=\"success\",\napplication=~\"$application\"}[$__range]))\r\n    /\r\n    sum(increase({__name__=~\".*_api_requests_total\",\n    application=~\"$application\"}[$__range]))\r\n  ),\r\n  0\r\n)\n",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "Success Rate by Api (Elapsed time)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\n    sum by (api) (\r\n     (rate({__name__=~\".*_api_requests_total\",application=~\"$application\",status=\"success\",api=~\"$api\"}[1m])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (api) (\r\n rate({__name__=~\".*_api_requests_total\",application=~\"$application\",api=~\"$api\"}[1m])\r\n    ))\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate(Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "clamp_min(\n100 *\r\n(\r\n  sum(\r\n    rate({__name__=~\".*_api_requests_total\",application=~\"$application\",status=~\"failed\"}[1m])\r\n  )\r\n)\r\n/\r\n(\r\n  sum(\r\n    rate({__name__=~\".*_api_requests_total\",application=~\"$application\"}[1m])\r\n  )\r\n),\n0\n)\r\n",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Error Rate (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "clamp_min(\n100 *\r\n(\r\n  sum(\r\n    increase({__name__=~\".*_api_requests_total\",application=~\"$application\",status=~\"failed\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum(\r\n    increase({__name__=~\".*_api_requests_total\",application=~\"$application\"}[$__range])\r\n  )\r\n),\n0\r\n)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Error Rate by Api (Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\n    sum by (api)(\r\n      rate({__name__=~\".*_api_requests_total\",\r\n            application=~\"$application\",\r\n            status=\"failed\",\r\n            api=~\"$api\"}[1m])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (api)(\r\n      rate({__name__=~\".*_api_requests_total\",\r\n            application=~\"$application\",\r\n            api=~\"$api\"}[1m])\r\n    )\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate by Uri (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\n    sum by (api)(\r\n      rate({__name__=~\".*_api_requests_total\",\r\n        application=~\"$application\",\r\n        status!=\"success\",\r\n        api=~\"$api\"\r\n      }[$__range])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (api)(\r\n      rate({__name__=~\".*_api_requests_total\",\r\n        application=~\"$application\",\r\n        api=~\"$api\"\r\n      }[$__range])\r\n    )\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request duration(Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, api)(\n    rate(\n      {__name__=~\".*_api_request_duration_seconds_bucket\",\n      api=~\"$api\"\n      }\n      [1m]\n    )\n  )\n) * 1000"
    }
   ]
  },
  {
   "title": "Summary APi Requests(Elapsed time)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  1000 *\r\n  (\r\n    sum by (application, api, status) (\r\n      rate({__name__=~\".*_api_request_duration_seconds_sum\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[1m])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (application,api, status) (\r\n      rate({__name__=~\".*_api_request_duration_seconds_count\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[1m])\r\n    )\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le,application,api, status) (\r\nrate({__name__=~\".*_api_request_duration_seconds_bucket\",application=~\"$application\",\r\n\r\n        api=~\"$api\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nmax by (application,api, status) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, application,api, status) (\r\nrate({__name__=~\".*_api_request_duration_seconds_bucket\",application=~\"$application\",\r\n\r\n        api=~\"$api\"}[1m])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.50,\r\n  sum by (le, application,api, status)(\r\n    rate((\r\n  {__name__=~\".*_api_request_duration_seconds_bucket\",\n application=~\"$application\",\r\n\r\n api=~\"$api\"}\n  [1m]\r\n    )\n    )\r\n  )\r\n)\r",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le, application,api, status)(\r\n    rate({__name__=~\".*_api_request_duration_seconds_bucket\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.99,\r\n  sum by (le, application,api, status)(\r\n    rate({__name__=~\".*_api_request_duration_seconds_bucket\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(\r\n  sum by (application,api, status)(\r\n    increase({\r__name__=~\".*_api_request_duration_seconds_count\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[1m]\r\n    )\r\n  )\r\n)\r"
    }
   ]
  },
  {
   "title": "Summary APi Requests(Last $__range)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  1000 *\r\n  (\r\n    sum by (application, api, status) (\r\n      rate({__name__=~\".*_api_request_duration_seconds_sum\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[$__range])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (application,api, status) (\r\n      rate({__name__=~\".*_api_request_duration_seconds_count\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[$__range])\r\n    )\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le,application,api, status) (\r\nrate({__name__=~\".*_api_request_duration_seconds_bucket\",application=~\"$application\",\r\n\r\n        api=~\"$api\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nmax by (application,api, status) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, application,api, status) (\r\nrate({__name__=~\".*_api_request_duration_seconds_bucket\",application=~\"$application\",\r\n\r\n        api=~\"$api\"}[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.50,\r\n  sum by (le, application,api, status)(\r\n    rate((\r\n  {__name__=~\".*_api_request_duration_seconds_bucket\",\n application=~\"$application\",\r\n\r\n api=~\"$api\"}\n  [$__range]\r\n    )\n    )\r\n  )\r\n)\r",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le, application,api, status)(\r\n    rate({__name__=~\".*_api_request_duration_seconds_bucket\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.99,\r\n  sum by (le, application,api, status)(\r\n    rate({__name__=~\".*_api_request_duration_seconds_bucket\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(\r\n  sum by (application,api, status)(\r\n    increase({\r__name__=~\".*_api_request_duration_seconds_count\",\r\n        application=~\"$application\",\r\n\r\n        api=~\"$api\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r"
    }
   ]
  },
  {
   "title": "Summary Top 5 URI P99 (Elapsed time )",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  histogram_quantile(\r\n    0.99,\r\n    sum by (le, api, status)(\r\n      rate(\r{__name__=~\".*_api_request_duration_seconds_bucket\",\n           api=~\"$api\"\r\n        }[1m]\r\n      )\r\n    )\r\n  ) * 1000\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Summary Top 5 URI P99 (Last $__range)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  histogram_quantile(\r\n    0.99,\r\n    sum by (le, api, status)(\r\n      rate(\r{__name__=~\".*_api_request_duration_seconds_bucket\",\n           api=~\"$api\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  ) * 1000\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total Request By Uri (Elapsed time)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(\r\n  sum by(api,status)(\r\n    increase(\r\n      {__name__=~\".*_api_request_duration_seconds_count\",\n      api=~\"$api\"}\n      [1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": " {{api}}  {{status}}"
    }
   ]
  },
  {
   "title": "Total Request By Uri (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(\r\n  sum by(api,status)(\r\n    increase(\r\n      {__name__=~\".*_api_request_duration_seconds_count\",\n      api=~\"$api\"}\n      [$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": " {{api}}  {{status}}"
    }
   ]
  },
  {
   "title": "Summary Request Count by Uri (Elapsed time)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(sum by (api)(\r\n  increase(\r\n    {__name__=~\".*_api_requests_total\",\r\n     application=~\"$application\",\r\n     status=\"success\",\r\n     api=~\"$api\"}\r\n  [1m])\r\n))",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "floor(sum by (api)(\r\n  increase(\r\n    {__name__=~\".*_api_requests_total\",\r\n     application=~\"$application\",\r\n     status=\"failed\",\r\n     api=~\"$api\"}\r\n  [1m])\r\n))\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "floor(\n  sum by(api)(\n    increase(\n      {__name__=~\".*_api_requests_total\",api=~\"$api\", application=~\"$application\"}[1m]\n    )\n  )\n)\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Summary Request Count by Uri (Last $__range)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(sum by (api)(\r\n  increase(\r\n    {__name__=~\".*_api_requests_total\",\r\n     application=~\"$application\",\r\n     status=\"success\",\r\n     api=~\"$api\"}\r\n  [$__range])\r\n))",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "floor(sum by (api)(\r\n  increase(\r\n    {__name__=~\".*_api_requests_total\",\r\n     application=~\"$application\",\r\n     status=\"failed\",\r\n     api=~\"$api\"}\r\n  [$__range])\r\n))\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "floor(\n  sum by(api)(\n    increase(\n      {__name__=~\".*_api_requests_total\",api=~\"$api\", application=~\"$application\"}[$__range]\n    )\n  )\n)\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Summary Request Time on Range",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le, api) (\r\n    rate({__name__=~\".*_api_request_duration_seconds_bucket\",api=~\"$api\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "1000 *\r\nmax by (api) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, api) (\r\n      rate({__name__=~\".*_api_request_duration_seconds_bucket\",api=~\"$api\"}[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "1000* (sum by(api)  (rate({__name__=~\".*_api_request_duration_seconds_sum\",api=~\"$api\"}[$__range]))\r\n/\r\nsum by(api)  (rate({__name__=~\".*_api_request_duration_seconds_count\",api=~\"$api\"}[$__range])))",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "floor(\r\n  sum by(api)(\r\n    increase(\r\n      {__name__=~\".*_api_request_duration_seconds_count\",api=~\"$api\"}[$__range]\r\n    )\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Total request(Elapsed time)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 207 },
   "targets": [
    {
     "expr": "floor(\r\n  sum(\r\n    increase(\r\n      {__name__=~\".*_api_requests_total\"}[1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Total request(Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "floor(\r\n  sum(\r\n    increase(\r\n      {__name__=~\".*_api_requests_total\"}[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "status count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 233 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(\nsum by(status)(\r\n  increase(\r\n    {__name__=~\".*_api_requests_total\"}[$__range]\r\n  )\r\n))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}