{
 "title": "outbound api (httpclient)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(fbb_http_client_requests_seconds_count,application)"
    }
   },
   {
    "name": "uri",
    "query": {
     "query": "label_values(fbb_http_client_requests_seconds_count{application=~\"$application\"},uri)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(fbb_http_client_requests_seconds_count{uri=~\"$uri\"}, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate(Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\nsum(rate({__name__=~\".*_http_client_requests_seconds_count\",status=~\"2..\",application=~\"$application\"}[1m]))\r\n    /\r\n    sum(rate({__name__=~\".*_http_client_requests_seconds_count\",application=~\"$application\"}[1m]))\r\n  ),\r\n  0\r\n)\n",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "Success Rate (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",status=~\"2..\",application=~\"$application\"}[$__range])\r\n\r\n)\r\n/\r\r\n sum(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",application=~\"$application\"}[$__range])\r\n  )\r\n\r\n)\n\n\r\n\r\r\r\n",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "Success Rate by Uri (Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\n    sum by (uri) (\r\n      rate({__name__=~\".*_http_client_requests_seconds_count\",\r\n            status=~\"2..\",\r\n            uri=~\"$uri\"}[1m])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (uri) (\r\n      rate({__name__=~\".*_http_client_requests_seconds_count\",\r\n            uri=~\"$uri\"}[1m])\r\n    )\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Success Rate by Uri (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 *\r\n  (\r\n    sum by (uri) (\r\n      rate({__name__=~\".*_http_client_requests_seconds_count\",\r\n            status=~\"2..\",\r\n            uri=~\"$uri\"}[$__range])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (uri) (\r\n      rate({__name__=~\".*_http_client_requests_seconds_count\",\r\n            uri=~\"$uri\"}[$__range])\r\n    )\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate(Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "clamp_min(\n100 *\r\n(\r\n  sum(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",status=~\"4..|5..\"}[1m])\r\n  )\r\n)\r\n/\r\n(\r\n  sum(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\"}[1m])\r\n  )\r\n),\n0\n)\r\n",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Error Rate (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "clamp_min(\n100 *\r\n(\r\n  sum(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",status=~\"4..|5..\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\"}[$__range])\r\n  )\r\n),\n0\r\n)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Error Rate by Uri (Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "clamp_min(\n100 *\r\n(\r\n  sum by(uri)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",status=~\"4..|5..\",uri=~\"$uri\"}[1m])\r\n  )\r\n)\r\n/\r\n(\r\n  sum by(uri)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",uri=~\"$uri\"}[1m])\r\n  )\r\n),\n0\r\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate by Uri (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by(uri)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",status=~\"4..|5..\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n/\r\n(\r\n  sum by(uri)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_count\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request duration(Elapsed time )",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, uri)(\n    rate(\n      {__name__=~\".*_http_client_requests_seconds_bucket\",\n      uri=~\"$uri\"\n      }\n      [1m]\n    )\n  )\n) * 1000"
    }
   ]
  },
  {
   "title": "Summary HTTP Client Requests(Elapsed time)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  1000 *\r\n  (\r\n    sum by (application, method, uri, status) (\r\n      rate({__name__=~\".*_http_client_requests_seconds_sum\",\r\n        application=~\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[1m])\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (application, method, uri, status) (\r\n      rate({__name__=~\".*_http_client_requests_seconds_count\",\r\n        application=~\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[1m])\r\n    )\r\n  ),\r\n  0\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le,application, method, uri, status) (\r\nrate({__name__=~\".*_http_client_requests_seconds_bucket\",application=~\"$application\",method=~\"$method\",uri=~\"$uri\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nmax by (application, method, uri, status) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, application, method, uri, status) (\r\nrate({__name__=~\".*_http_client_requests_seconds_bucket\",application=~\"$application\",method=~\"$method\",uri=~\"$uri\"}[1m])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.50,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n(\n  {__name__=~\".*_http_client_requests_seconds_bucket\",\n  application=~\"$application\",\n  method=~\"$method\",\n  uri=~\"$uri\"}\n  [1m]\r\n    )\n    )\r\n  )\r\n)\r",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le, application, method, uri, status)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_bucket\",\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.99,\r\n  sum by (le, application, method, uri, status)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_bucket\",\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(\r\n  sum by (application, method, uri, status)(\r\n    increase({\r__name__=~\".*_http_client_requests_seconds_count\",\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[1m]\r\n    )\r\n  )\r\n)\r"
    }
   ]
  },
  {
   "title": "Summary HTTP Client Requests(Last $__range)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\r\n  1000 *\r\n  (\r\n    sum by (application, method, uri, status) (\r\n      rate(\r\n        {__name__=~\".*_http_client_requests_seconds_sum\",\r\n         application=~\"$application\",\r\n         method=~\"$method\",\r\n         uri=~\"$uri\"}\r\n        [$__range]\r\n      )\r\n    )\r\n  )\r\n  /\r\n  (\r\n    sum by (application, method, uri, status) (\r\n      rate(\r\n        {__name__=~\".*_http_client_requests_seconds_count\",\r\n         application=~\"$application\",\r\n         method=~\"$method\",\r\n         uri=~\"$uri\"}\r\n        [$__range]\r\n      )\r\n    )\r\n  )\r\n)\r\n\r",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le,application, method, uri, status) (\r\nrate({__name__=~\".*_http_client_requests_seconds_bucket\",application=~\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nmax by (application, method, uri, status) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, application, method, uri, status) (\r\nrate({__name__=~\".*_http_client_requests_seconds_bucket\",application=~\"$application\",method=~\"$method\",uri=~\"$uri\"}[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.50,\r\n  sum by (le, application, method, uri, status)(\r\n    rate(\r\n(\n  {__name__=~\".*_http_client_requests_seconds_bucket\",\n  application=~\"$application\",\n  method=~\"$method\",\n  uri=~\"$uri\"}\n  [$__range]\r\n    )\n    )\r\n  )\r\n)\r",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le, application, method, uri, status)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_bucket\",\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.99,\r\n  sum by (le, application, method, uri, status)(\r\n    rate({__name__=~\".*_http_client_requests_seconds_bucket\",\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(\r\n  sum by (application, method, uri, status)(\r\n    increase({\r__name__=~\".*_http_client_requests_seconds_count\",\r\n        application=\"$application\",\r\n        method=~\"$method\",\r\n        uri=~\"$uri\"\r\n      }[$__range]\r\n    )\r\n  )\r\n)\r"
    }
   ]
  },
  {
   "title": "Summary Top 5 URI P99 (Elapsed time )",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  histogram_quantile(\r\n    0.99,\r\n    sum by (le, method, uri, status)(\r\n      rate(\r{__name__=~\".*_http_client_requests_seconds_bucket\",\n           uri=~\"$uri\",method=~\"$method\"\r\n        }[1m]\r\n      )\r\n    )\r\n  ) * 1000\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Summary Top 5 URI P99 (Last $__range)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "topk(\r\n  5,\r\n  histogram_quantile(\r\n    0.99,\r\n    sum by (le, method, uri, status)(\r\n      rate(\r{__name__=~\".*_http_client_requests_seconds_bucket\",\n           uri=~\"$uri\",method=~\"$method\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  ) * 1000\r\n)\r\n",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total Request By Uri (Elapsed time)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(\r\n  sum by(uri,status,method)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",\n      uri=~\"$uri\"}\n      [1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{method}} {{uri}}  {{status}}"
    }
   ]
  },
  {
   "title": "Total Request By Uri (Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(\r\n  sum by(uri,status,method)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",\n      uri=~\"$uri\"}\n      [$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{method}}{{uri}} :   {{status}}"
    }
   ]
  },
  {
   "title": "Summary Request Count by Uri (Elapsed time)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",\n      status=~\"2..\",\n      uri=~\"$uri\"}\n      [1m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",status=~\"4..|5..\",uri=~\"$uri\"}[1m]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",uri=~\"$uri\"}[1m]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Summary Request Count by Uri (Last $__range)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",status=~\"2..\",uri=~\"$uri\"}[$__range]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",status=~\"4..|5..\",uri=~\"$uri\"}[$__range]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",uri=~\"$uri\"}[$__range]\r\n    )\r\n  )\r\n)\r",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Summary Average Request Time on Range",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.01,\r\n  sum by (le, uri) (\r\n    rate({__name__=~\".*_http_client_requests_seconds_bucket\",uri=~\"$uri\"}[$__range])\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000 *\r\nmax by (uri) (\r\n  histogram_quantile(\r\n    1,\r\n    sum by (le, uri) (\r\n      rate({__name__=~\".*_http_client_requests_seconds_bucket\",uri=~\"$uri\"}[$__range])\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1000* (sum by(uri)  (rate({__name__=~\".*_http_client_requests_seconds_sum\",uri=~\"$uri\"}[$__range]))\r\n/\r\nsum by(uri)  (rate({__name__=~\".*_http_client_requests_seconds_count\",uri=~\"$uri\"}[$__range])))",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "floor(\r\n  sum by(uri)(\r\n    increase(\r\n      {__name__=~\".*_http_client_requests_seconds_count\",uri=~\"$uri\"}[$__range]\r\n    )\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Total request(Elapsed time)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 222 },
   "targets": [
    {
     "expr": "floor(sum(increase(fbb_http_client_requests_seconds_count[1m])))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Total request(Last $__range)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 235 },
   "targets": [
    {
     "expr": "floor(sum(increase({__name__=~\".*_http_client_requests_seconds_count\"}[$__range])))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "status count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 248 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status)({__name__=~\".*_http_client_requests_seconds_count\"})",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}